# limit flood
if ($programname == "plasmashell" or $programname == "warp-svc") then {
   if ($syslogseverity > 4) then { stop }
}

# :programname,isequal,"plasmashell" /var/log/plasmashell.log
# & stop
# :programname,isequal,"warp-svc" /var/log/warp.log

# Uncomment the following to stop logging anything that matches the last rule.
# Doing this will stop logging those messages to the file
# normally containing kern.* messages (eg, /var/log/kern.log)
# & stop
